//! Shared PDF document template (foundation §8).
//!
//! Every generated PDF in the suite wraps its report-specific body in one
//! branded shell so all outputs read consistently: a **cover page** (branding,
//! headline stat panels, a meta table, and a bottom-pinned disclaimer +
//! copyright) and **body pages** carrying a running legal footer. A consumer
//! builds only its body HTML + the cover summary pieces; `render` returns a
//! self-contained HTML document for the WeasyPrint service.
//!
//! The exact CSS/layout here is iterated on in `scripts/report-preview.html`
//! (rendered via `scripts/report-preview.sh` — no api rebuild). Keep the two in
//! sync when changing the design.
//!
//! Branding is configured once via env (`SITELENS_ORG_NAME`,
//! `SITELENS_SUPPORT_EMAIL`) and mirrored by the web app's `NEXT_PUBLIC_*`.

use std::env;

/// Company legal name for copyright/branding (env `SITELENS_ORG_NAME`).
pub fn org_name() -> String {
    env::var("SITELENS_ORG_NAME").unwrap_or_else(|_| "KeshavTech LLC".to_string())
}

/// Support contact address (env `SITELENS_SUPPORT_EMAIL`).
pub fn support_email() -> String {
    env::var("SITELENS_SUPPORT_EMAIL").unwrap_or_else(|_| "support@msalia.org".to_string())
}

/// Product name — the app is SiteLens.
pub const PRODUCT: &str = "SiteLens";

/// The standard survey-data disclaimer shown on every report cover.
pub const DISCLAIMER: &str = "This report is generated by SiteLens from data supplied by the \
    user. Values are derived from that source data and its stated accuracy. It does not \
    constitute a certified survey or engineering document unless sealed by a licensed \
    professional.";

/// The short fine print shown in the running page footer.
pub const FOOTER_FINE_PRINT: &str = "Not a sealed survey document";

/// A headline stat panel on the cover (the indigo/dark blocks). `accent` picks
/// the brand-accent background; otherwise it renders on the dark block.
pub struct StatPanel {
    pub label: String,
    pub value: String,
    pub note: String,
    pub accent: bool,
}

impl StatPanel {
    pub fn new(
        label: impl Into<String>,
        value: impl Into<String>,
        note: impl Into<String>,
        accent: bool,
    ) -> Self {
        StatPanel {
            label: label.into(),
            value: value.into(),
            note: note.into(),
            accent,
        }
    }
}

/// One labelled fact in the cover meta table.
pub struct Fact {
    pub label: String,
    pub value: String,
}

impl Fact {
    pub fn new(label: impl Into<String>, value: impl Into<String>) -> Self {
        Fact {
            label: label.into(),
            value: value.into(),
        }
    }
}

/// A report to render into the shared shell.
pub struct Document {
    /// Cover headline, e.g. "As-Built Stakeout Report".
    pub title: String,
    /// Optional cover sub-headline (report kind / frame).
    pub subtitle: Option<String>,
    /// Prose paragraph on the cover describing this specific output.
    pub summary: String,
    /// Headline stat panels (1–2) — the indigo/dark blocks.
    pub panels: Vec<StatPanel>,
    /// Compact key/value meta table under the panels.
    pub facts: Vec<Fact>,
    /// Report-specific body HTML (sections/tables) — rendered after the cover.
    /// Use the shared body classes (`sec`, `count`, `cols2`, `info`, `notebox`,
    /// `alert-ok`, `alert-none`, `st`/`st pass|warn|fail`, `n`).
    pub body_html: String,
    /// Human date the report was generated, e.g. "2026-07-07".
    pub generated_on: String,
    /// Four-digit year for the copyright line, e.g. "2026".
    pub year: String,
}

/// HTML-escape text destined for element content.
pub fn esc(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// Escape a string for use inside a double-quoted CSS `content:` value.
fn css_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// The SiteLens compass mark as inline SVG (mirrors web `app/icon.svg`). Sized
/// by the `.brand .logo svg` rule so it can't overflow onto the wordmark.
fn logo_svg() -> &'static str {
    r##"<svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
<defs><linearGradient id="g" x1="0" y1="0" x2="32" y2="32" gradientUnits="userSpaceOnUse">
<stop stop-color="#818cf8"/><stop offset="1" stop-color="#8b5cf6"/></linearGradient></defs>
<rect width="32" height="32" rx="8" fill="url(#g)"/>
<g stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none">
<circle cx="16" cy="16" r="9"/>
<polygon points="20.9 10.3 18.1 18.1 10.3 20.9 13.1 13.1" fill="#ffffff" stroke="none"/></g></svg>"##
}

fn panels_html(panels: &[StatPanel]) -> String {
    if panels.is_empty() {
        return String::new();
    }
    let cells: String = panels
        .iter()
        .map(|p| {
            format!(
                "<div class=\"panel {cls}\"><div class=\"plabel\">{label}</div>\
                 <div class=\"pvalue\">{value}</div><div class=\"pnote\">{note}</div></div>",
                cls = if p.accent { "accent" } else { "dark" },
                label = esc(&p.label),
                value = esc(&p.value),
                note = esc(&p.note),
            )
        })
        .collect();
    format!("<div class=\"panels\">{cells}</div>")
}

fn facts_html(facts: &[Fact]) -> String {
    if facts.is_empty() {
        return String::new();
    }
    let rows: String = facts
        .iter()
        .map(|f| {
            format!(
                "<div class=\"fact\"><dt>{}</dt><dd>{}</dd></div>",
                esc(&f.label),
                esc(&f.value)
            )
        })
        .collect();
    format!("<dl class=\"facts\">{rows}</dl>")
}

/// Render the full, self-contained HTML document (cover + body + footer chrome).
pub fn render(doc: &Document) -> String {
    let org = org_name();
    let footer = format!(
        "© {} {} · Generated by {} · {}",
        doc.year, org, PRODUCT, FOOTER_FINE_PRINT
    );

    let subtitle_html = doc
        .subtitle
        .as_deref()
        .map(|s| format!("<p class=\"subtitle\">{}</p>", esc(s)))
        .unwrap_or_default();

    format!(
        r#"<!DOCTYPE html><html><head><meta charset="utf-8"><style>
@page {{
  size: letter;
  margin: 14mm 14mm 15mm;
  /* Margin boxes don't inherit body styles — set the font on each explicitly. */
  @bottom-left {{ content: "{footer}"; font-family: 'Inter', 'DejaVu Sans', Arial, sans-serif; font-size: 7pt; color: #98a2b3; }}
  @bottom-right {{ content: "Page " counter(page) " of " counter(pages); font-family: 'Inter', 'DejaVu Sans', Arial, sans-serif; font-size: 7pt; color: #98a2b3; }}
}}
/* The cover carries its own branding + copyright, so it has no running footer. */
@page cover {{ @bottom-left {{ content: ""; }} @bottom-right {{ content: ""; }} }}
* {{ box-sizing: border-box; }}
body {{ font-family: 'Inter', 'DejaVu Sans', Arial, sans-serif; color: #101828; font-size: 9pt; line-height: 1.45; }}

/* Cover fills the printable page so the footer pins to the bottom. */
.cover {{ page: cover; display: flex; flex-direction: column; min-height: 240mm; page-break-after: always; }}
.spacer {{ flex: 1 1 auto; }}
/* No flex `gap` (WeasyPrint ignores it) — the logo gutter is a margin, and the
   SVG is sized to its box so it can't overflow onto the wordmark. */
.brand {{ display: flex; align-items: center; }}
.brand .logo {{ display: block; width: 34px; height: 34px; margin-right: 3.5mm; }}
.brand .logo svg {{ display: block; width: 34px; height: 34px; }}
.brand .btext {{ display: flex; flex-direction: column; }}
.brand .name {{ font-size: 10.5pt; font-weight: 700; line-height: 1.2; letter-spacing: -0.01em; }}
.brand .by {{ font-size: 7.5pt; color: #667085; line-height: 1.2; }}
.hero {{ margin-top: 20mm; }}
.hero h1 {{ font-size: 26pt; font-weight: 800; letter-spacing: -0.02em; margin: 0; }}
.hero .subtitle {{ color: #475467; font-size: 11pt; margin: 2.5mm 0 0; }}
.hero .summary {{ color: #344054; font-size: 9.5pt; margin: 6mm 0 0; max-width: 155mm; }}
.panels {{ display: flex; margin-top: 10mm; }}
.panel {{ flex: 1; display: flex; flex-direction: column; min-height: 46mm; padding: 7mm; color: #fff; }}
.panel.accent {{ background: #6366f1; }}
.panel.dark {{ background: #101828; }}
.panel .plabel {{ font-size: 11pt; font-weight: 600; }}
.panel .pvalue {{ font-size: 40pt; font-weight: 800; line-height: 1; margin-top: 3mm; }}
.panel .pnote {{ font-size: 8.5pt; opacity: 0.85; margin-top: auto; }}
.facts {{ margin-top: 10mm; border-top: 1px solid #e4e7ec; }}
.facts .fact {{ display: flex; justify-content: space-between; padding: 2mm 0; border-bottom: 1px solid #eef0f3; }}
.facts dt {{ color: #667085; font-size: 9.5pt; margin: 0; }}
.facts dd {{ font-weight: 600; font-size: 9.5pt; margin: 0; text-align: right; font-variant-numeric: tabular-nums; }}
.cover-foot {{ padding-top: 8mm; }}
.cover-foot .disclaimer {{ color: #667085; font-size: 8pt; line-height: 1.45; max-width: 170mm; }}
.cover-foot .copyright {{ color: #98a2b3; font-size: 8pt; margin-top: 3mm; }}

/* ---- Body ---- */
.body .sec {{ font-size: 11pt; font-weight: 700; margin: 6mm 0 2.5mm; letter-spacing: -0.01em; }}
.body .sec:first-child {{ margin-top: 0; }}
.body .count {{ color: #667085; font-weight: 400; }}
/* Report info + disclaimers side by side; margin gutter (flex `gap` unsupported). */
.cols2 {{ display: flex; align-items: stretch; }}
.cols2 > div {{ flex: 1 1 0; min-width: 0; display: flex; flex-direction: column; }}
.cols2 > div:first-child {{ margin-right: 8mm; }}
.info {{ flex: 1; background: #f9fafb; padding: 3.5mm 4mm; display: flex; flex-direction: column; gap: 1.5mm; }}
.info > div {{ display: flex; justify-content: space-between; gap: 4mm; }}
.info .k {{ color: #667085; }}
.info .v {{ font-weight: 600; text-align: right; }}
.notebox {{ flex: 1; background: #f9fafb; padding: 3.5mm 4mm; }}
.notebox p {{ margin: 0 0 2mm; font-size: 8.5pt; }}
.notebox p:last-child {{ margin-bottom: 0; }}
.notebox .fine {{ color: #667085; font-size: 8pt; }}
.alert-ok {{ display: flex; align-items: center; gap: 2mm; border: 1px solid #16a34a40; background: #16a34a0d; color: #15803d; padding: 2.5mm 3.5mm; font-size: 9pt; }}
.alert-none {{ border: 1px solid #eef0f3; background: #f9fafb; color: #667085; padding: 2.5mm 3.5mm; font-size: 9pt; }}
table {{ width: 100%; border-collapse: collapse; margin-top: 1mm; font-size: 8.5pt; }}
th, td {{ border-bottom: 1px solid #eef0f3; padding: 1.6mm 2mm; text-align: left; }}
th {{ color: #667085; font-weight: 500; border-bottom-color: #e4e7ec; }}
th.n, td.n {{ text-align: right; font-variant-numeric: tabular-nums; }}
.st {{ font-weight: 600; }}
.st.pass {{ color: #067647; }} .st.warn {{ color: #b54708; }} .st.fail {{ color: #b42318; }}
.st.unmatched, .st.novert {{ color: #667085; }}
</style></head><body>
<section class="cover">
  <header class="brand">
    <span class="logo">{logo}</span>
    <span class="btext"><span class="name">{product}</span><span class="by">by {org}</span></span>
  </header>
  <div class="hero">
    <h1>{title}</h1>
    {subtitle}
    <p class="summary">{summary}</p>
  </div>
  {panels}
  {facts}
  <div class="spacer"></div>
  <footer class="cover-foot">
    <p class="disclaimer">{disclaimer}</p>
    <p class="copyright">© {year} {org}. All rights reserved. · Generated {generated_on}.</p>
  </footer>
</section>
<section class="body">{body}</section>
</body></html>"#,
        footer = css_str(&footer),
        logo = logo_svg(),
        product = PRODUCT,
        org = esc(&org),
        title = esc(&doc.title),
        subtitle = subtitle_html,
        summary = esc(&doc.summary),
        panels = panels_html(&doc.panels),
        facts = facts_html(&doc.facts),
        disclaimer = esc(DISCLAIMER),
        year = esc(&doc.year),
        generated_on = esc(&doc.generated_on),
        body = doc.body_html,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn doc() -> Document {
        Document {
            title: "As-Built Stakeout Report".into(),
            subtitle: Some("Design vs as-built".into()),
            summary: "3 points compared.".into(),
            panels: vec![
                StatPanel::new("Points compared", "3", "Checked against design.", true),
                StatPanel::new("Within tolerance", "100%", "3 pass · 0 fail", false),
            ],
            facts: vec![
                Fact::new("Project", "BAPS Mandir"),
                Fact::new("Points", "3"),
            ],
            body_html: "<h2 class=\"sec\">Errors</h2><div class=\"alert-ok\">None</div>".into(),
            generated_on: "2026-07-07".into(),
            year: "2026".into(),
        }
    }

    #[test]
    fn render_wraps_body_in_branded_shell() {
        let html = render(&doc());
        assert!(html.contains("class=\"cover\""));
        assert!(html.contains("As-Built Stakeout Report"));
        assert!(html.contains("by KeshavTech LLC"));
        assert!(html.contains("class=\"alert-ok\""));
        // Running footer + bottom-pinned cover footer + Inter font on margin boxes.
        assert!(html.contains("Generated by SiteLens"));
        assert!(html.contains(FOOTER_FINE_PRINT));
        assert!(html.contains("counter(page)"));
        assert!(html.contains("class=\"spacer\""));
        assert!(html.contains("'Inter'"));
        // Sharp panels (no border-radius on .panel).
        assert!(html.contains("class=\"panel accent\""));
        assert!(html.contains("does not")); // disclaimer
    }

    #[test]
    fn org_name_honors_env_default() {
        assert_eq!(org_name(), "KeshavTech LLC");
    }

    #[test]
    fn cover_content_is_escaped() {
        let mut d = doc();
        d.facts = vec![Fact::new("Site", "A & <B>")];
        let html = render(&d);
        assert!(html.contains("A &amp; &lt;B&gt;"));
    }
}
